name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: yarn install
        run: |
          yarn install --frozen-lockfile --verbose

      - name: Run build
        run: |
          yarn build

      - name: Run jest
        run: |
          time yarn test
          time yarn test
          time yarn test
          time yarn test
          time yarn test

      - name: Run jest with ts-jest
        run: |
          time yarn test:ts-jest
          time yarn test:ts-jest
          time yarn test:ts-jest
          time yarn test:ts-jest
          time yarn test:ts-jest

      - name: Run jest with swc
        run: |
          time yarn test:swc
          time yarn test:swc
          time yarn test:swc
          time yarn test:swc
          time yarn test:swc
